name: CI

on:
  push:
    branches: [ "master" ]
    tags: ["v*.*.*"]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cargo fmt --check
        run: cargo fmt --check
  build:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  
  release:
    name: Release
    needs: [build]
    if: startsWith(github.ref_type, 'tag')
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: [ aarch64-unknown-linux-gnu, x86_64-unknown-linux-gnu ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          tar czvf ../../../schellen-bridge-rs-${{ matrix.target }}.tar.gz schellen-bridge-rs
          cd -
      - uses: actions/upload-artifact@v3
        with:
          name: schellen-bridge-rs
          path: schellen-bridge-rs-*
